#!/usr/bin/env bash
# To install Nginx on web server
sudo apt update
sudo apt-get -y install nginx
new_loc="
location / {
	return 200 'Hello World!'
}
"
nginx_config_file="/etc/nginx/sites-available/default"

sudo sed -i -e "/location \/ {/,/}/c$new_loc" "$nginx_config_file"
sudo nginx -s reload
