#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo chmod -R 755 /etc/nginx/sites-enabled

sudo echo "server {
        listen 80;

        server_name _;

        location = /redirect_me {
                return 301 altayseer.tech;
        }
}" | tee /etc/nginx/sites-enabled/default

sudo service nginx restart
