#!/usr/bin/env bash
# configure error page

# Update package list
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Start nginx service
sudo service nginx start

sudo echo "Ceci n'est pas une page" | tee /var/www/html/404.html

# Create Nginx configuration for redirection
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
                return 301 http://example.com/new_page;
    }

    location / {
                try_files $uri $uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
                root /var/www/html;
                internal;
    }
}
" | sudo tee /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
