#!/usr/bin/env bash
# Install nginx server and configure it to return custom response

sudo service nginx start
sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo chmod -R 755 /etc/nginx/sites-enabled

sudo echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;


        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location / {
                try_files \$uri \$uri/ =404;
		add_header X-Served-By $hostname;
        }

        error_page 404 /404.html;
        location = /404.html {
                internal;
        }
}" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
