#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt -y update && sudo apt -y upgrade
sudo apt install haproxy -y
sudo service haproxy start

sudo chown -R "$USER":"$USER" /etc/haproxy
sudo chmod -R 755 /etc/haproxy

sudo echo "global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

backend mybackend
    balance roundrobin
    server 414087-web-01 100.24.244.24:80 check
    server 414087-web-02 52.87.222.58:80 check
" | tee /etc/haproxy/haproxy.cfg

sudo chown -R "$USER":"$USER" /etc/default
sudo chmod -R 755 /etc/default

sudo echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo service haproxy restart
