#!/usr/bin/env bash
# debugging to make nginx listen on ort 80
sudo sed -i '/^listen 80 default_server;/c\listen 80;' /etc/nginx/sites-available/default
sudo sed -i '/^listen [::]:80 default_server;/c\listen [::]:80;' /etc/nginx/sites-available/default
sudo service nginx restart
