#!/usr/bin/env bash
# Bash script displays numbers from 1 to 100

for ((i=0; i<101; i++)); do
    a=(($i%3))
    b=(($i%5))
    if [ $a -eq 0 ] then
        echo "Fizz"
    elif [ $b -eq 0] then
        echo "Buzz"
    elif [ $b -eq 0] && [ $a -eq 0 ] then
        echo "FizzBuzz"
    else
        echo "$i"
    fi
done
