#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and 1 "Hi"
list="Best School"
i=0
while [ $i -lt 10 ]; do
    echo $list
    if [ $i -eq 8 ]; then
    	echo "Hi"
    fi
    ((i++))
done
