#!/usr/bin/env bash
# Bash script gives you information about the school file.

doc="school"
if [ -e $doc ] then
	echo "school file exists"
	if [ -s $doc ] then
		echo "school file is not empty"
		if [ -f $doc ] then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi