#!/usr/bin/env bash
# update the user to nginx
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
# Update Nginx configuration to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

pkill apache2

# Restart Nginx to apply changes
sudo -u service nginx restart
