#!/usr/bin/env bash
# Update Nginx configuration to run as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Update Nginx configuration to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2

# Restart Nginx to apply changes
sudo -u service nginx restart
