#!/usr/bin/env bash
# To reload Gunicorn in a graceful way

# Use pgrep to find Gunicorn PIDs
gunicorn_pids=$(pgrep gunicorn)

# Check if Gunicorn processes are running
if [ -z "$gunicorn_pids" ]; then
    echo "No Gunicorn processes found."
    exit 1
fi

# Send HUP signal to each Gunicorn process
for pid in $gunicorn_pids; do
    if kill -HUP "$pid"; then
        echo "Sent HUP signal to Gunicorn process $pid."
    else
        echo "Failed to send HUP signal to Gunicorn process $pid."
    fi
done

exit 0

